# This is a basic workflow to help you get started with Actions
name: Topicos

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master, main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  task-1:
    if: ${{ contains(github.event.comment.body, '#001') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: # "nome do topico"
          content-filepath: # .github/content/issues/"nome do topico".md

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.2
        with:
          template: .github/content/closeIssues/01-closed.md
          vars: |
            repoUrl: https://github.com/${{github.repository_owner}}/${{ github.event.repository.name }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: ${{ steps.template.outputs.result }}

      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: 1
